apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    app: pw
spec:
  type: LoadBalancer
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
    nodePort: 31000
  selector:
    app: pw
